// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIPhonebook.Models
{
    public partial class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LoginId { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        
        public int SecurityQuestionId_1 { get; set; }
        public byte[] SecurityAnswerHash_1 { get; set; }
        public byte[] SecurityAnswerSalt_1 { get; set; }

        public int SecurityQuestionId_2 { get; set; }
        public byte[] SecurityAnswerHash_2 { get; set; }
        public byte[] SecurityAnswerSalt_2 { get; set; }

        public SecurityQuestion SecurityQuestion_1 {  get; set; }
        public SecurityQuestion SecurityQuestion_2 {  get; set; }
    }
}